#pragma once

#define REGISTRY_WINAPI_VERSION_WINXP 0x0501
#define REGISTRY_WINAPI_VERSION_WS03 0x0502
#define REGISTRY_WINAPI_VERSION_WIN6 0x0600
#define REGISTRY_WINAPI_VERSION_VISTA 0x0600
#define REGISTRY_WINAPI_VERSION_WS08 0x0600
#define REGISTRY_WINAPI_VERSION_LONGHORN 0x0600
#define REGISTRY_WINAPI_VERSION_WIN7 0x0601
#define REGISTRY_WINAPI_VERSION_WIN8 0x0602
#define REGISTRY_WINAPI_VERSION_WINBLUE 0x0603
#define REGISTRY_WINAPI_VERSION_WINTHRESHOLD 0x0A00
#define REGISTRY_WINAPI_VERSION_WIN10 0x0A00

#if !defined(REGISTRY_USE_WINAPI_VERSION)
#if defined(_WIN32_WINNT)
#define REGISTRY_USE_WINAPI_VERSION _WIN32_WINNT
#elif defined(WINVER)
#define REGISTRY_USE_WINAPI_VERSION WINVER
#else
// By default use Windows Vista API on compilers that support it and XP on the others
#if (defined(_MSC_VER) && _MSC_VER < 1500) || defined(REGISTRY_WINAPI_IS_MINGW)
#define REGISTRY_USE_WINAPI_VERSION REGISTRY_WINAPI_VERSION_WINXP
#else
#define REGISTRY_USE_WINAPI_VERSION REGISTRY_WINAPI_VERSION_WIN6
#endif
#endif
#endif